### ISSUE TITLE
ember-require-module brings in outdated ember-cli-babel

### ISSUE THREAD

**Issue by bjornharrtell** [offirgolan/ember-validators#101]
The following outdated versions are found in your project:

* ember-cli-babel@6.18.0, currently used by:
  * ember-require-module@0.3.0
    * Depends on ember-cli-babel@^6.9.2
    * Added by ember-cp-validations@4.0.0-beta.12

**Comment by snewcomer** [comment]
This should be fixed?  Feel free to reopen if not!

https://github.com/offirgolan/ember-validators/blob/master/package.json

**Comment by bjornharrtell** [comment]
Ah wrong project, should be for ember-cp-validations, sorry!
