### ISSUE TITLE
Nested  `ds-error` validations don't work anymore

### ISSUE THREAD

**Issue by herzzanu** [offirgolan/ember-validators#110]
It looks like the `ds-error` validatior stopped working for nested errors. I assume this https://github.com/offirgolan/ember-validators/commit/f829984c8c28152f6e15d0b091308583fb1ac997 might have broken it.

The fix is most likely on this line https://github.com/offirgolan/ember-validators/commit/f829984c8c28152f6e15d0b091308583fb1ac997#diff-ca376f14c1cb0e5696506e00be4f0fa42e7212370c4b5e5bb8eef4970fdcdfceL25

In this case `model[path]` would work if the `path` is a simple key like `errors`. However, if the `path` is a nested key like `foo.errors` it won't work. We could fix this by doing `model.get(path)`. 

@snewcomer let me know if this is good for you and I can go ahead and create a PR.

**Comment by snewcomer** [comment]
That sounds great!  `get(model, path)`

**Comment by herzzanu** [comment]
Thanks for the quick reply @snewcomer Here's the PR https://github.com/offirgolan/ember-validators/pull/111
