### ISSUE TITLE
0.1.2 has breaking changes

### ISSUE THREAD

**Issue by fractalwolfe** [offirgolan/ember-validators#23]
The recently released 0.1.2 of this package has breaking changes, replacing the packaged in require-module with ember-require-module.

This change breaks offirgolan/ember-cp-validations v2.7.2 which we use, since it's dependency is set to `~0.1.0` meaning it will pull in this version.

I suggest you read up on http://semver.org/, breaking changes should not be part of a patch release.

**Comment by offirgolan** [comment]
@fractalwolfe I'm not sure how this change affects v2.x since ember-validators is only part of 3.x. A patch for ember-cp-validations was released along with 0.1.2 of this package which should not cause any breaking changes.

**Comment by fractalwolfe** [comment]
Turns out I was wrong, seems we get v3.1.0 of ember-cp-validations, despite asking for 2.7.2 in our package.json. It also seems however that npm doesn't want to install the latest patch (3.1.1). Will need to investigate this further.

**Comment by fractalwolfe** [comment]
I found the cause. Our framework package with lists ember-cp-validations as a dependency has it locked to `3.1.0`, which in turn depends on ember-validators `~0.1.0`, causing it to fail because of the 0.1.2 release. Had it been released as 1.2.0 everything would have been fine.

So I suppose the lesson from this is don't release breaking changes as patches, packages that depend on them might be locked to a specific version and not get the fix, as is the case here. :)

**Comment by offirgolan** [comment]
@fractalwolfe this wasn't expected to be a breaking change. Sorry for causing you some trouble! I'll leave this open for a bit just in case anyone else is running into this issue. Thanks for updating the issue with your findings 😄

**Comment by Turbo87** [comment]
indeed I just ran into the same issue. since I used `ember install` to install `ember-cp-validations` it caused the dependency to be pinned to `3.1.0` and I didn't get the `3.1.1` patch release.

**Comment by offirgolan** [comment]
@Turbo87 Yeah that was a mistake I made on the ember-cp-validations side which unfortunately led to this issue. Sorry for the trouble!
