### ISSUE TITLE
Support moment object in date validator

### ISSUE THREAD

**Issue by ondrejsevcik** [offirgolan/ember-validators#58]
Hi, it would be nice to support moment/computed property in date validator. I have a scenario where some field date must be after another field's date. I guess this example explains it pretty well.

```js
expirationDate: [
  validator('date', {
    // model.createdDate is momentjs object
    after: computed.alias('model.createdDate'),
    precision: 'day',
    message: "Expiration date can't be before creation date.",
  })
]
```

Do you know how to make it work with current date validator? Otherwise, I can provide PR.

**Comment by offirgolan** [comment]
PR is welcome! I think it makes a lot of sense to support moment objects.

**Comment by ondrejsevcik** [comment]
It seems it's working. I just used it wrong. I should not provide `format` option.
